version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./storage:/var/www/storage
            - php_socket:/var/run/php
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_CONNECTION=pgsql
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_DATABASE=laravel
            - DB_USERNAME=laravel
            - DB_PASSWORD=secret
            - CACHE_DRIVER=redis
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        depends_on:
            - postgres
            - redis

    nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - php_socket:/var/run/php
        ports:
            - "8088:80"
        depends_on:
            - app

    postgres:
        image: postgres:15
        container_name: postgres
        environment:
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: laravel
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    redis:
        image: redis:7
        container_name: redis
        ports:
            - "6379:6379"

volumes:
    postgres_data:
    php_socket:
